### PR TITLE
SSH to node that did not join the cluster

### LINKED ISSUE #146: Can't SSH to node that has not yet joined the cluster
**What happened**:
There is a validation that aborts the SSH command in case the node was not found: https://github.com/gardener/gardenctl-v2/blob/master/pkg/cmd/ssh/options.go#L466-L471

The operation should not abort in case the node did not yet join the cluster as that could also be the reason why the user wants to troubleshoot this node.

**What you expected to happen**:
An information could be printed in case the node was not found but it should still continue.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
gardenctl continues with the SSH operation in case the node was not found (e.g. node failed to joined the cluster)

**Which issue(s) this PR fixes**:
Fixes #146

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Fixed an issue where it was not possible to SSH to a node that has not yet joined the cluster
```

### CODE REVIEW

File: pkg/cmd/ssh/options.go [hunk 1]
```diff
@@ -463,11 +464,17 @@ func (o *SSHOptions) Run(f util.Factory) error {
...
+	if o.NodeName != "" {
+		nodeHostname, err = getNodeHostname(ctx, o, shootClient, o.NodeName)
+		if err != nil {
+			if !apierrors.IsNotFound(err) {
+				return fmt.Errorf("failed to determine hostname for node: %w", err)
+			}
+
+			fmt.Fprintf(o.IOStreams.Out, "Node with name %q not found. Wrong name provided or this node did not yet join the cluster, continuing anyways: %v\n", o.NodeName, err)
+			nodeHostname = o.NodeName
+		}
```
Comment (holgerkoser) [inline pkg/cmd/ssh/options.go:477]:
```suggestion
	var nodeHostname string
	if o.NodeName != "" {
          node, err := getShootNode(ctx, o, shootClient, currentTarget)
          if err == nil {
            nodeHostname, err = getNodeHostname(node)
            if err != nil {
              return err
            }
          } else if apierrors.IsNotFound(err) {
            fmt.Fprintf(o.IOStreams.Out, "Node with name %q not found. Wrong name provided or this node did not yet join the cluster, continuing anyways: %v\n", o.NodeName, err)
            nodeHostname = o.NodeName
          } else {
            return fmt.Errorf("failed to determine hostname for node: %w", err)
          }
```

I think it would be more clear to not mix `getNodeHostname` and `getShootNode`

Comment (holgerkoser) [reply pkg/cmd/ssh/options.go:477]: I not sure if this proposal is correct but it should give you the idea.

File: pkg/cmd/ssh/options.go [hunk 2]
```diff
@@ -1036,7 +1025,12 @@ func writeToTemporaryFile(key []byte) (string, error) {
 	return f.Name(), nil
 }
 
-func getNodeHostname(node *corev1.Node) (string, error) {
+func getNodeHostname(ctx context.Context, o *SSHOptions, shootClient client.Client, nodeName string) (string, error) {
```
Comment (holgerkoser) [inline pkg/cmd/ssh/options.go:1028]: I would keep the old signature

File: pkg/cmd/ssh/options.go (hunk 1 above)
Comment (petersutter) [reply pkg/cmd/ssh/options.go:477]: ✅

**Review by holgerkoser — APPROVED** [review]
/lgtm
