### PR TITLE
`ssh`: Abort keepalive on not found

### LINKED ISSUE #232: Abort keepalive bastion if not found
**What happened**:
When running the `g ssh` command it creates a bastion resource and continuously sets the keepalive annotation on the bastion.
However if the bastion was deleted in the meantime (e.g. the local machine was hibernated) it prints out
```
Failed to keep bastion alive: bastions.operations.gardener.cloud "cli-zj4efox3" not found
Failed to keep bastion alive: bastions.operations.gardener.cloud "cli-zj4efox3" not found
...
```

**What you expected to happen**:
In case of not found error, it should abort with a corresponding message instead of trying to annotate the bastion over and over again that does not exist anymore.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by petersutter**
**What this PR does / why we need it**:
The bastion keepalive is now aborted in case the bastion was deleted

**Which issue(s) this PR fixes**:
Fixes #232

**Special notes for your reviewer**:

**Release note**:

```bugfix user
`ssh`: the command will now exit in case the `Bastion` resource was deleted
```

### CODE REVIEW

File: pkg/cmd/ssh/options.go [hunk 1]
```diff
@@ -151,6 +151,103 @@ var (
 
 		return cmd.Run()
 	}
+	// waitForSignal informs the user about their SSHOptions and keeps the
+	// bastion alive until gardenctl exits.
+	waitForSignal = func(ctx context.Context, o *SSHOptions, shootClient client.Client, bastion *operationsv1alpha1.Bastion, nodeHostname string, nodePrivateKeyFiles []string, signalChan <-chan struct{}) error {
```
Comment (holgerkoser) [inline pkg/cmd/ssh/options.go:156]: Seeee my comment in the other ssh PR.

**Review by holgerkoser — APPROVED** [review]
/lgtm

File: pkg/cmd/ssh/options.go (hunk 1 above)
Comment (petersutter) [reply pkg/cmd/ssh/options.go:156]: as just discussed we leave it as is for now until we get feedback from users that it is confusing when targeting managed seed (for which there is always a shoot) and running ssh
